# Generated by Django 2.2.13 on 2020-08-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateField(auto_now=True, null=True)),
                ('last_modified_by', models.TextField(null=True)),
                ('state', models.CharField(max_length=2)),
                ('status', models.TextField(default='Submitted')),
                ('year', models.IntegerField()),
            ],
        ),
    ]
